---
:concurrency: 10
:timeout: 4
:max_retries: 1
:queues:
  # See here to understand priorities: https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues
  # Use powers of 2: higher priority groups are checked twice as often.
  - [update_postcode, 8]
  - [queue_postcode, 1]
:schedule:
  queue_oldest_postcodes_for_updating:
    every: '1s'
    class: PostcodesCollectionWorker
