---
:concurrency: 10
:timeout: 4
:max_retries: 1
:queues:
  - [queue_ons, 8]
  - [update_postcode, 8]
  - [queue_postcode, 1]
:scheduler:
  :schedule:
    queue_oldest_postcodes_for_updating:
      every: '1s'
      class: PostcodesCollectionWorker
